% plotfreq
ic = 12;
figure; 
pop_newtimef( EEG, 0, ic, [-1000, 496], [3, 0.5], ...
    'topovec', EEG.icawinv(:,ic), 'elocs', EEG.chanlocs, ...
    'chaninfo', EEG.chaninfo, 'caption', ['IC ', num2str(ic)], ...
    'baseline',[150 500],'nfreqs', 50, 'freqs', [5 80], ...
    'plotphase', 'off', 'padratio', 1);